#!/bin/sh
mac_address_changer () {
for i in `ifconfig | grep eth | awk -F" " '{print $1}'`
    do
    FILE=/etc/sysconfig/network-orig/ifcfg-
    correctmac=$(ifconfig $i |grep -i hwadd| gawk -Fdr  '{print $2}'|sed 's/^[ ]//')
    wrongmac=$(grep -i hwaddr $FILE$i|gawk -F= '{print $2}')
    echo $FILE $correctmac  $wrongmac   
    sed -i "s;$wrongmac;$correctmac;g" $FILE$i
    done
#else echo interface $interface doesnt exist, run ifconfig to see which interface you are trying to change mac address of
}

#interface=${1:?specify which ethernet interface}
#USAGE="#macchanger eth0"
#if [ $#  -gt 1 ] ; then echo  $USAGE 1>&2;exit;fi
mac_address_changer
